import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireCapability } from "@/features/auth/services/authorization-service";
import { RotationControls } from "@/features/scheduling/components/scheduling-forms";
import { listRotations } from "@/features/scheduling/services/scheduling-service";

export const metadata: Metadata = { title: "Schedule Rotations" };
export default async function RotationsPage({ searchParams }: Readonly<{ searchParams: Promise<{ created?: string }> }>) { const account = await requireCapability("scheduling.view"); if (!["platform_administrator", "youth_pastor", "staff_member"].includes(account.role)) notFound(); const [rotations, params] = await Promise.all([listRotations(), searchParams]); return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link className="text-sm font-semibold text-sky-700" href="/scheduling">← Back to Scheduling</Link><h1 className="mt-3 text-3xl font-bold">Recurring rotations</h1><p className="mt-2 text-slate-600">Manage recurring patterns and generate future schedule occurrences.</p></div><Link className="min-h-11 rounded-lg bg-sky-700 px-4 py-3 font-semibold text-white" href="/scheduling/rotations/new">Create rotation</Link></div>{params.created === "1" ? <p className="rounded-lg bg-emerald-50 p-3 text-emerald-800">Rotation created.</p> : null}<div className="grid gap-4 lg:grid-cols-2">{rotations.map((rotation) => <article className="rounded-xl border bg-white p-5 shadow-sm" key={rotation.id}><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">{rotation.name}</h2><p className="text-sm text-slate-600">{rotation.recurrencePattern} · {rotation.responsibility}</p></div><span className="capitalize">{rotation.status}</span></div><RotationControls rotation={rotation} /></article>)}</div>{!rotations.length ? <p className="rounded-xl border bg-white p-6 text-slate-600">No recurring rotations have been created.</p> : null}</div>; }
