import "server-only";
import {z} from "zod";
import {createClient} from "@/lib/supabase/server";
import type{CustomFormAssignmentSummary,CustomFormDraft,CustomFormSubmissionDetail,CustomFormSubmissionSummary,CustomFormTemplateRow,MyCustomForm}from"@/features/forms/types/custom-forms";
type RpcError={message:string;code?:string};
async function rpc(name:string,args:Record<string,unknown>={}){const s=await createClient();return (s.rpc as unknown as (n:string,a:Record<string,unknown>)=>Promise<{data:unknown;error:RpcError|null}>)(name,args)}
const row=(value:unknown)=>value as Record<string,unknown>;
export async function listCustomFormTemplates():Promise<CustomFormTemplateRow[]>{const{data,error}=await rpc("list_custom_form_templates");if(error||!Array.isArray(data))return[];return data.map(value=>{const r=row(value);return{templateId:String(r.template_id),name:String(r.name),description:r.description as string|null,templateStatus:String(r.template_status),versionId:r.version_id as string|null,versionNumber:r.version_number as number|null,versionTitle:r.version_title as string|null,versionStatus:r.version_status as string|null,fieldCount:Number(r.field_count),assignmentCount:Number(r.assignment_count)}})}
export async function listMyCustomForms():Promise<MyCustomForm[]>{const{data,error}=await rpc("list_my_custom_forms");if(error||!Array.isArray(data))return[];return data.map(value=>{const r=row(value);return{assignmentId:String(r.assignment_id),assignmentType:r.assignment_type as MyCustomForm["assignmentType"],subjectStudentId:r.subject_student_id as string|null,title:String(r.title),versionNumber:Number(r.version_number),submissionId:r.submission_id as string|null,submissionStatus:r.submission_status as string|null,assignedAt:String(r.assigned_at)}})}
export type OpenCustomFormResult={success:true;draft:CustomFormDraft}|{success:false;reason:"not_found"|"unavailable"};
export async function openCustomForm(assignmentId:string,studentId:string|null):Promise<OpenCustomFormResult>{
  if(!z.string().uuid().safeParse(assignmentId).success||(studentId!==null&&!z.string().uuid().safeParse(studentId).success))return{success:false,reason:"not_found"};
  const{data,error}=await rpc("open_custom_form_assignment",{p_assignment_id:assignmentId,p_subject_student_id:studentId});
  if(error)return{success:false,reason:["22P02","42501","P0002"].includes(error.code??"")?"not_found":"unavailable"};
  return data?{success:true,draft:data as CustomFormDraft}:{success:false,reason:"not_found"};
}
export async function listCustomFormSubmissions():Promise<CustomFormSubmissionSummary[]>{const{data,error}=await rpc("list_custom_form_submissions",{p_template_id:null});if(error||!Array.isArray(data))return[];return data.map(value=>{const r=row(value);return{submissionId:String(r.submission_id),templateId:String(r.template_id),versionId:String(r.version_id),versionNumber:Number(r.version_number),title:String(r.title),assignmentType:r.assignment_type as CustomFormSubmissionSummary["assignmentType"],submissionStatus:String(r.submission_status),submittedAt:r.submitted_at as string|null,subjectStudentId:r.subject_student_id as string|null,subjectHouseholdId:r.subject_household_id as string|null,subjectVolunteerProfileId:r.subject_volunteer_profile_id as string|null}})}
export async function listCustomFormAssignments():Promise<CustomFormAssignmentSummary[]>{const{data,error}=await rpc("list_custom_form_assignments");if(error||!Array.isArray(data))return[];return data.map(value=>{const r=row(value);return{assignmentId:String(r.assignment_id),versionId:String(r.version_id),title:String(r.title),versionNumber:Number(r.version_number),assignmentType:r.assignment_type as CustomFormAssignmentSummary["assignmentType"],targetId:(r.event_id??r.student_id??r.household_id??r.volunteer_profile_id??null) as string|null,assignedAt:String(r.assigned_at)}})}
export async function getCustomFormSubmission(submissionId:string){const{data,error}=await rpc("get_custom_form_submission",{p_submission_id:submissionId});if(error||!data)throw new Error(error?.message??"Custom Form submission not found.");return data as CustomFormSubmissionDetail}
export function isDuplicateCustomFormAssignmentError(error:unknown){const message=error instanceof Error?error.message.toLowerCase():"";return message.includes("this form is already assigned to that target")||message.includes("custom_form_assignments_one_active_target")||message.includes("duplicate key")}
export async function runCustomFormRpc(name:string,args:Record<string,unknown>){const{data,error}=await rpc(name,args);if(error)throw new Error(error.message);return data}
