import "server-only";
import {createAdminClient} from "@/lib/supabase/admin";
import {createClient} from "@/lib/supabase/server";
import {inspectCompletedDocument,sanitizeCompletedDocumentFilename} from "@/features/forms/services/completed-document-validation.mjs";
import type {AvailableDocumentVersion,DocumentSubmissionSummary} from "@/features/forms/types/document-submissions";
type R={data:unknown;error:{message:string}|null};
async function rpc(name:string,args:Record<string,unknown>={}):Promise<R>{const c=await createClient();return (c as unknown as {rpc:(n:string,a:Record<string,unknown>)=>Promise<R>}).rpc(name,args)}
function data<T>(r:R):T{if(r.error)throw new Error(r.error.message);return r.data as T}
export async function listAvailableDocumentVersions():Promise<AvailableDocumentVersion[]>{const rows=data<Record<string,unknown>[]>(await rpc("list_available_document_versions"))??[];return rows.map(r=>({studentId:String(r.student_id),studentName:String(r.student_name),householdId:String(r.household_id),templateVersionId:String(r.template_version_id),templateName:String(r.template_name),versionNumber:Number(r.version_number),documentKind:r.document_kind as AvailableDocumentVersion["documentKind"]}))}
export async function listDocumentSubmissions():Promise<DocumentSubmissionSummary[]>{const rows=data<Record<string,unknown>[]>(await rpc("list_document_submissions"))??[];return rows.map(r=>({submissionId:String(r.submission_id),studentId:String(r.student_id),studentName:String(r.student_name),householdId:String(r.household_id),templateVersionId:String(r.template_version_id),templateName:String(r.template_name),versionNumber:Number(r.version_number),documentKind:r.document_kind as DocumentSubmissionSummary["documentKind"],uploadSource:r.upload_source as DocumentSubmissionSummary["uploadSource"],digitalStatus:r.digital_status as DocumentSubmissionSummary["digitalStatus"],lifecycleStatus:String(r.lifecycle_status),paperCopyOnFile:Boolean(r.paper_copy_on_file),reviewState:r.review_state?String(r.review_state):null,medicalVerified:Boolean(r.medical_verified),expiresOn:r.expires_on?String(r.expires_on):null,supersedesSubmissionId:r.supersedes_submission_id?String(r.supersedes_submission_id):null,isSuperseded:Boolean(r.is_superseded),originalFileName:r.original_file_name?String(r.original_file_name):null}))}
export async function prepareDocumentSubmissionUpload(input:{studentId:string;templateVersionId:string;extension:"pdf"|"jpg"|"png";supersedesSubmissionId:string}){const authorization=data<{submissionId:string;bucket:string;objectPath:string}>(await rpc("prepare_document_submission_upload",{p_student_id:input.studentId,p_template_version_id:input.templateVersionId,p_object_id:crypto.randomUUID(),p_extension:input.extension,p_supersedes_submission_id:input.supersedesSubmissionId||null}));const c=await createClient();const signed=await c.storage.from(authorization.bucket).createSignedUploadUrl(authorization.objectPath);if(signed.error)throw new Error(signed.error.message);return {...authorization,token:signed.data.token}}
export async function finalizeDocumentSubmissionUpload(submissionId:string,rawFilename:string){const authorization=data<{bucket:string;objectPath:string;actorProfileId:string}>(await rpc("authorize_document_submission_finalization",{p_submission_id:submissionId}));const trusted=createAdminClient();const downloaded=await trusted.storage.from(authorization.bucket).download(authorization.objectPath);if(downloaded.error)throw new Error(downloaded.error.message);const verified=inspectCompletedDocument(new Uint8Array(await downloaded.data.arrayBuffer()));if(!authorization.objectPath.endsWith(`.${verified.extension}`))throw new Error("The uploaded file extension does not match its actual content.");const result=await (trusted as unknown as {rpc:(n:string,a:Record<string,unknown>)=>Promise<R>}).rpc("finalize_document_submission_upload",{p_submission_id:submissionId,p_actor_profile_id:authorization.actorProfileId,p_original_file_name:sanitizeCompletedDocumentFilename(rawFilename,verified.extension),p_content_type:verified.contentType,p_file_size_bytes:verified.fileSizeBytes,p_checksum_sha256:verified.checksumSha256});data(result)}
export async function authorizeAndDownloadSubmission(submissionId:string){const authorization=data<{bucket:string;objectPath:string;fileName:string;contentType:string}>(await rpc("authorize_document_submission_download",{p_submission_id:submissionId}));const trusted=createAdminClient();const downloaded=await trusted.storage.from(authorization.bucket).download(authorization.objectPath);if(downloaded.error)throw new Error(downloaded.error.message);return {blob:downloaded.data,fileName:authorization.fileName,contentType:authorization.contentType}}
export async function runSubmissionWorkflow(name:string,submissionId:string,reason:string){data(await rpc(name,{p_submission_id:submissionId,p_reason:reason||null}))}
