import "server-only";
import {createClient}from"@/lib/supabase/server";
import type{VisitorCardDetail,VisitorCardEventOption,VisitorCardListItem,VisitorCardMatch,VisitorCardStatus}from"@/features/forms/types/visitor-cards";

async function rpc(name:string,args:Record<string,unknown>={}){const client=await createClient();return(client.rpc as unknown as(n:string,a:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>)(name,args)}
const row=(value:unknown)=>value as Record<string,unknown>;
export async function runVisitorCardRpc(name:string,args:Record<string,unknown>){const{data,error}=await rpc(name,args);if(error)throw new Error(error.message);return data}
export async function listVisitorCards(status:VisitorCardStatus|null=null):Promise<VisitorCardListItem[]>{const{data,error}=await rpc("list_visitor_cards",{p_status:status});if(error)throw new Error(error.message);if(!Array.isArray(data))return[];return data.map(value=>{const r=row(value);return{visitorCardId:String(r.visitor_card_id),visitorName:String(r.visitor_name),visitDate:String(r.visit_date),eventName:r.event_name as string|null,source:r.source as VisitorCardListItem["source"],status:r.status as VisitorCardStatus,hasEmail:Boolean(r.has_email),hasPhone:Boolean(r.has_phone),followUpEmail:Boolean(r.follow_up_email),followUpPhone:Boolean(r.follow_up_phone),createdAt:String(r.created_at)}})}
export async function listVisitorCardEvents():Promise<VisitorCardEventOption[]>{const{data,error}=await rpc("list_visitor_card_events");if(error)throw new Error(error.message);if(!Array.isArray(data))return[];return data.map(value=>{const r=row(value);return{eventId:String(r.event_id),eventName:String(r.event_name),startsAt:String(r.starts_at)}})}
export async function getVisitorCardDetail(id:string):Promise<VisitorCardDetail>{const{data,error}=await rpc("get_visitor_card_detail",{p_visitor_card_id:id});if(error||!data)throw new Error(error?.message??"Visitor Card not found.");return data as VisitorCardDetail}
export async function listVisitorCardMatches(id:string):Promise<VisitorCardMatch[]>{const{data,error}=await rpc("list_visitor_card_possible_matches",{p_visitor_card_id:id});if(error)throw new Error(error.message);if(!Array.isArray(data))return[];return data.map(value=>{const r=row(value);return{personId:String(r.person_id),studentId:r.student_id as string|null,householdId:r.household_id as string|null,displayName:String(r.display_name),matchSignals:Array.isArray(r.match_signals)?r.match_signals.map(String):[]}})}
