import { z } from "zod";
const id = z.string().uuid();
const optionalId = z.preprocess((v) => v === "" ? null : v, id.nullable());
const optionalText = z.preprocess((v) => typeof v === "string" && v.trim() === "" ? null : v, z.string().trim().max(1000).nullable());
export const scheduleSchema = z.object({ name: z.string().trim().min(1).max(200), ministryContext: optionalText, eventId: optionalId, startsAt: z.coerce.date(), endsAt: z.coerce.date(), timezone: z.string().trim().min(1).max(100).default("America/Chicago"), notes: optionalText }).refine((v) => v.endsAt > v.startsAt, { message: "End must follow start." });
export const locationSchema = z.object({ scheduleId: id, name: z.string().trim().min(1).max(150), notes: optionalText });
export const positionSchema = z.object({ scheduleId: id, locationId: optionalId, responsibility: z.string().trim().min(1).max(150), requiredCount: z.coerce.number().int().min(1).max(50) });
export const assignmentSchema = z.object({ positionId: id, profileId: id, startsAt: z.coerce.date(), endsAt: z.coerce.date(), override: z.preprocess((v) => v === "on", z.boolean()), overrideReason: optionalText }).refine((v) => v.endsAt > v.startsAt);
export const lifecycleSchema = z.object({ scheduleId: id, status: z.enum(["published", "cancelled", "completed"]), allowUnfilled: z.preprocess((v) => v === "on", z.boolean()) });
export const assignmentIdSchema = z.object({ assignmentId: id });
export const rotationSchema = z.object({ name: z.string().trim().min(1).max(200), pattern: z.enum(["weekly", "biweekly", "monthly"]), weekday: z.coerce.number().int().min(0).max(6), monthlyOrdinal: z.preprocess((v) => v === "" ? null : v, z.coerce.number().int().min(1).max(5).nullable()), startsOn: z.string().date(), endsOn: z.preprocess((v) => v === "" ? null : v, z.string().date().nullable()), startsAt: z.string().time(), endsAt: z.string().time(), timezone: z.string().trim().min(1).max(100), scheduleName: z.string().trim().min(1).max(200), ministryContext: optionalText, responsibility: z.string().trim().min(1).max(150), locationName: optionalText, profileId: optionalId });
export const rotationStatusSchema = z.object({ rotationId: id, status: z.enum(["active", "paused", "ended"]) });
export const generationSchema = z.object({ rotationId: id, through: z.string().date() });
