"use client";

import Link from "next/link";
import {useActionState,useState} from "react";
import {archiveCustomAssignmentAction,archiveCustomSubmissionAction,archiveCustomTemplateAction,createCustomAssignmentAction,createCustomTemplateAction,createCustomVersionAction,publishCustomVersionAction,retireCustomVersionAction,saveCustomFieldAction} from "@/features/forms/actions/custom-form-actions";
import type{CustomFormActionState,CustomFormAssignmentSummary,CustomFormAssignmentTargets,CustomFormAssignmentType,CustomFormSubmissionSummary,CustomFormTemplateRow,MyCustomForm}from"@/features/forms/types/custom-forms";

const initial:CustomFormActionState={success:false};
const input="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3";
function Message({state}:{state:CustomFormActionState}){return state.message?<p className={state.success?"text-sm text-emerald-700":"text-sm text-rose-700"}>{state.message}</p>:null}

function AssignmentForm({versions,targets}:{versions:CustomFormTemplateRow[];targets:CustomFormAssignmentTargets}){
 const [state,action,pending]=useActionState(createCustomAssignmentAction,initial);
 const [assignmentType,setAssignmentType]=useState<CustomFormAssignmentType>("student");
 const options=assignmentType==="event"?targets.events:assignmentType==="student"?targets.students:assignmentType==="household"?targets.households:assignmentType==="volunteer"?targets.volunteers:[];
 const targetLabel=assignmentType==="event"?"Event":assignmentType==="student"?"Student":assignmentType==="household"?"Household":"Volunteer";
 return <form action={action} className="space-y-3 rounded-xl border bg-white p-5"><h3 className="font-bold">Assign published form</h3><label className="text-sm font-semibold">Published version<select className={input} name="versionId" required><option value="">Select</option>{versions.filter(v=>v.versionStatus==="published").map(v=><option key={v.versionId!} value={v.versionId!}>{v.name} · v{v.versionNumber}</option>)}</select></label><label className="text-sm font-semibold">Assignment type<select className={input} name="assignmentType" value={assignmentType} onChange={event=>setAssignmentType(event.target.value as CustomFormAssignmentType)}><option value="student">Student</option><option value="household">Household</option><option value="volunteer">Volunteer</option><option value="event">Event</option><option value="general_ministry">General ministry</option></select></label>{assignmentType==="general_ministry"?<p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-600">General Ministry assignments apply without a specific target.</p>:<label className="text-sm font-semibold">{targetLabel}<select className={input} key={assignmentType} name="targetId" required><option value="">Select {targetLabel.toLowerCase()}</option>{options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>{!options.length?<span className="mt-1 block font-normal text-amber-700">No eligible {targetLabel.toLowerCase()} targets are available.</span>:null}</label>}<Message state={state}/><button disabled={pending} className="min-h-11 rounded-lg bg-violet-700 px-4 font-semibold text-white">Create assignment</button></form>
}
function ManagerForms({templates,assignments,submissions,targets}:{templates:CustomFormTemplateRow[];assignments:CustomFormAssignmentSummary[];submissions:CustomFormSubmissionSummary[];targets:CustomFormAssignmentTargets}){
 const [templateState,templateAction,templatePending]=useActionState(createCustomTemplateAction,initial);
 const [versionState,versionAction,versionPending]=useActionState(createCustomVersionAction,initial);
 const [fieldState,fieldAction,fieldPending]=useActionState(saveCustomFieldAction,initial);
 const versions=templates.filter(t=>t.versionId);
 return <section className="space-y-5">
  <div><p className="text-sm font-semibold text-violet-700">Custom Forms management</p><h2 className="text-2xl font-bold">Templates, fields, and assignments</h2><p className="mt-1 text-sm text-slate-600">Build operational forms only. Medical records and medical documentation belong in the Medical Release workflow.</p></div>
  <div className="grid gap-4 xl:grid-cols-2">
   <form action={templateAction} className="space-y-3 rounded-xl border bg-white p-5"><h3 className="font-bold">Create template</h3><label className="text-sm font-semibold">Name<input className={input} name="name" required maxLength={200}/></label><label className="text-sm font-semibold">Description<textarea className={`${input} py-2`} name="description" maxLength={2000}/></label><Message state={templateState}/><button disabled={templatePending} className="min-h-11 rounded-lg bg-violet-700 px-4 font-semibold text-white">Create template</button></form>
   <form action={versionAction} className="space-y-3 rounded-xl border bg-white p-5"><h3 className="font-bold">Create immutable-version draft</h3><label className="text-sm font-semibold">Template<select className={input} name="templateId" required><option value="">Select</option>{templates.filter(t=>t.templateStatus!=="archived").filter((t,i,a)=>a.findIndex(x=>x.templateId===t.templateId)===i).map(t=><option key={t.templateId} value={t.templateId}>{t.name}</option>)}</select></label><label className="text-sm font-semibold">Version title<input className={input} name="title" required/></label><label className="text-sm font-semibold">Instructions<textarea className={`${input} py-2`} name="instructions"/></label><Message state={versionState}/><button disabled={versionPending} className="min-h-11 rounded-lg bg-violet-700 px-4 font-semibold text-white">Create draft</button></form>
   <form action={fieldAction} className="space-y-3 rounded-xl border bg-white p-5"><h3 className="font-bold">Add controlled draft field</h3><label className="text-sm font-semibold">Draft version<select className={input} name="versionId" required><option value="">Select</option>{versions.filter(v=>v.versionStatus==="draft").map(v=><option key={v.versionId!} value={v.versionId!}>{v.name} · v{v.versionNumber}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Field key<input className={input} name="fieldKey" pattern="[a-z][a-z0-9_]*" required/></label><label className="text-sm font-semibold">Type<select className={input} name="fieldType"><option value="short_text">Short text</option><option value="long_text">Long text</option><option value="yes_no">Yes / No</option><option value="single_choice">Single choice</option><option value="multiple_choice">Multiple choice</option><option value="date">Date</option><option value="acknowledgment">Boolean acknowledgment</option></select></label></div><label className="text-sm font-semibold">Label<input className={input} name="label" required/></label><label className="text-sm font-semibold">Help text<input className={input} name="helpText"/></label><label className="text-sm font-semibold">Choice options (comma separated)<input className={input} name="choiceOptions"/></label><div className="flex gap-5"><label><input name="isRequired" type="checkbox"/> Required</label><label>Order <input className="ml-2 w-20 rounded border px-2 py-1" name="displayOrder" type="number" defaultValue="0" min="0"/></label></div><Message state={fieldState}/><button disabled={fieldPending} className="min-h-11 rounded-lg bg-violet-700 px-4 font-semibold text-white">Add field</button></form>
   <AssignmentForm versions={versions} targets={targets}/>
  </div>
  <div className="space-y-3"><h3 className="text-xl font-bold">Template and version history</h3>{versions.map(v=><article className="rounded-xl border bg-white p-4" key={v.versionId!}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{v.name} · v{v.versionNumber}</p><p className="text-sm text-slate-600">{v.versionTitle} · {v.fieldCount} fields · {v.assignmentCount} active assignments · {v.versionStatus}</p></div><div className="flex gap-2">{v.versionStatus==="draft"?<form action={publishCustomVersionAction}><input type="hidden" name="versionId" value={v.versionId!}/><button className="rounded-lg border px-3 py-2 font-semibold">Publish</button></form>:null}{v.versionStatus==="published"?<form action={retireCustomVersionAction}><input type="hidden" name="versionId" value={v.versionId!}/><button className="rounded-lg border px-3 py-2 font-semibold">Retire</button></form>:null}<form action={archiveCustomTemplateAction}><input type="hidden" name="templateId" value={v.templateId}/><button className="rounded-lg border border-rose-300 px-3 py-2 font-semibold text-rose-800">Archive template</button></form></div></div></article>)}</div>
  <div className="space-y-3"><h3 className="text-xl font-bold">Active assignments</h3>{assignments.map(a=><article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4" key={a.assignmentId}><div><p className="font-bold">{a.title} · v{a.versionNumber}</p><p className="text-sm capitalize text-slate-600">{a.assignmentType.replaceAll("_"," ")}{a.targetId?` · ${a.targetId}`:""}</p></div><form action={archiveCustomAssignmentAction}><input type="hidden" name="assignmentId" value={a.assignmentId}/><button className="rounded-lg border border-rose-300 px-3 py-2 font-semibold text-rose-800">Archive assignment</button></form></article>)}</div>
  <div className="space-y-3"><h3 className="text-xl font-bold">Retained submissions</h3>{submissions.map(s=><article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4" key={s.submissionId}><div><p className="font-bold">{s.title} · v{s.versionNumber}</p><p className="text-sm text-slate-600">{s.assignmentType.replaceAll("_"," ")} · {s.submissionStatus}{s.submittedAt?` · ${new Date(s.submittedAt).toLocaleString()}`:""}</p></div><div className="flex gap-2"><Link className="rounded-lg border px-3 py-2 font-semibold" href={`/permission-forms/submissions/${s.submissionId}`}>View retained response</Link>{s.submissionStatus==="submitted"?<form action={archiveCustomSubmissionAction}><input type="hidden" name="submissionId" value={s.submissionId}/><button className="rounded-lg border border-rose-300 px-3 py-2 font-semibold text-rose-800">Archive</button></form>:null}</div></article>)}{!submissions.length?<p className="rounded-xl border bg-white p-5 text-slate-600">No Custom Form submissions yet.</p>:null}</div>
 </section>
}

export function CustomFormsWorkspace({manager,templates,assignments,myForms,submissions,assignmentTargets}:{manager:boolean;templates:CustomFormTemplateRow[];assignments:CustomFormAssignmentSummary[];myForms:MyCustomForm[];submissions:CustomFormSubmissionSummary[];assignmentTargets:CustomFormAssignmentTargets}){return <div className="space-y-8">{manager?<ManagerForms templates={templates} assignments={assignments} submissions={submissions} targets={assignmentTargets}/>:null}<section className="space-y-3"><div><p className="text-sm font-semibold text-violet-700">My Forms</p><h2 className="text-2xl font-bold">Assigned operational forms</h2><p className="text-sm text-slate-600">Open a form, save each draft answer, then submit when every required response is complete.</p></div>{myForms.map(f=><Link className="block rounded-xl border bg-white p-5 hover:border-violet-300" href={`/permission-forms/my/${f.assignmentId}${f.subjectStudentId?`?student=${f.subjectStudentId}`:""}`} key={`${f.assignmentId}-${f.subjectStudentId??"self"}`}><div className="flex justify-between gap-3"><p className="font-bold">{f.title} · v{f.versionNumber}</p><span className="capitalize text-slate-600">{f.submissionStatus??"not started"}</span></div><p className="mt-1 text-sm capitalize text-slate-600">{f.assignmentType.replaceAll("_"," ")}</p></Link>)}{!myForms.length?<p className="rounded-xl border bg-white p-5 text-slate-600">No Custom Forms are assigned to you.</p>:null}</section></div>}
