"use client";
import {useState}from"react";
import {saveCustomAnswerAction,submitCustomFormAction}from"@/features/forms/actions/custom-form-actions";
import type{CustomFormDraft,CustomFormField}from"@/features/forms/types/custom-forms";

function Answer({assignmentId,submissionId,field,locked}:{assignmentId:string;submissionId:string;field:CustomFormField;locked:boolean}){const common={name:"value",disabled:locked};const[choiceValue,setChoiceValue]=useState(field.choiceValue??"");const[multipleChoiceValue,setMultipleChoiceValue]=useState(field.multipleChoiceValue??[]);let control:React.ReactNode;
 if(field.fieldType==="long_text")control=<textarea {...common} className="mt-1 min-h-28 w-full rounded-lg border p-3" defaultValue={field.textValue??""}/>;
 else if(field.fieldType==="short_text")control=<input {...common} className="mt-1 min-h-11 w-full rounded-lg border px-3" defaultValue={field.textValue??""}/>;
 else if(field.fieldType==="date")control=<input {...common} className="mt-1 min-h-11 rounded-lg border px-3" type="date" defaultValue={field.dateValue??""}/>;
 else if(field.fieldType==="single_choice")control=<select {...common} className="mt-1 min-h-11 w-full rounded-lg border px-3" value={choiceValue} onChange={event=>setChoiceValue(event.target.value)}><option value="">Select</option>{field.choiceOptions?.map(o=><option key={o} value={o}>{o}</option>)}</select>;
 else if(field.fieldType==="multiple_choice")control=<div className="mt-2 space-y-2">{field.choiceOptions?.map(o=><label className="block" key={o}><input {...common} type="checkbox" value={o} checked={multipleChoiceValue.includes(o)} onChange={event=>setMultipleChoiceValue(current=>event.target.checked?[...current,o]:current.filter(value=>value!==o))}/> {o}</label>)}</div>;
 else if(field.fieldType==="acknowledgment")control=<label className="mt-2 block"><input {...common} type="checkbox" value="true" defaultChecked={field.booleanValue===true}/> I acknowledge this statement (this is not an electronic signature).</label>;
 else control=<select {...common} className="mt-1 min-h-11 rounded-lg border px-3" defaultValue={field.booleanValue==null?"":String(field.booleanValue)}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select>;
 return <form action={saveCustomAnswerAction} className="rounded-xl border bg-white p-5"><input type="hidden" name="assignmentId" value={assignmentId}/><input type="hidden" name="submissionId" value={submissionId}/><input type="hidden" name="fieldId" value={field.fieldId}/><input type="hidden" name="fieldType" value={field.fieldType}/><label className="font-semibold">{field.label}{field.required?<span className="text-rose-700"> *</span>:null}</label>{field.helpText?<p className="text-sm text-slate-600">{field.helpText}</p>:null}{control}{!locked?<button className="mt-3 rounded-lg border px-3 py-2 font-semibold">Save draft answer</button>:null}</form>}
export function CustomFormRespondent({draft}:{draft:CustomFormDraft}){const locked=draft.status!=="draft";return <div className="space-y-5"><header><p className="text-sm font-semibold text-violet-700">My Forms</p><h1 className="text-3xl font-bold">{draft.title}</h1>{draft.instructions?<p className="mt-2 text-slate-600">{draft.instructions}</p>:null}<p className="mt-2 text-sm text-slate-600">Acknowledgments are boolean confirmations only and are never electronic signatures. Medical documentation belongs in the Medical Release workflow.</p></header>{draft.fields.map(f=><Answer assignmentId={draft.assignmentId} key={f.fieldId+"-"+(f.choiceValue??"")+"-"+(f.multipleChoiceValue?.join("|")??"")} submissionId={draft.submissionId} field={f} locked={locked}/>)}{!locked?<form action={submitCustomFormAction}><input type="hidden" name="submissionId" value={draft.submissionId}/><button className="min-h-11 rounded-lg bg-violet-700 px-5 font-bold text-white">Submit completed form</button><p className="mt-2 text-sm text-slate-600">Submission is rejected unless every required answer is complete.</p></form>:<p className="rounded-xl border bg-white p-5 font-semibold capitalize">Status: {draft.status}. Submitted content is retained and immutable.</p>}</div>}
