"use client";

import { useActionState } from "react";
import { setEventPermissionSlipRequirementAction } from "@/features/forms/actions/medical-permission-actions";
import type { EventPermissionSlipRequirement } from "@/features/forms/types/medical-permission";

export function EventPermissionSlipForm({ eventId, requirement, versions }: { eventId: string; requirement: EventPermissionSlipRequirement; versions: Array<{ versionId: string; label: string }> }) {
  const [state, action, pending] = useActionState(setEventPermissionSlipRequirementAction, { success: false });
  return <section className="space-y-4 rounded-xl border border-sky-200 bg-sky-50/50 p-5"><div><p className="text-sm font-semibold text-sky-700">Event documentation</p><h2 className="text-xl font-bold">Permission slip</h2><p className="text-sm text-slate-600">The selected published version is pinned to this Event. Changing or removing it archives the prior requirement and retains history.</p></div><form action={action} className="grid gap-3 md:grid-cols-[12rem_1fr_auto]"><input type="hidden" name="eventId" value={eventId}/><select className="min-h-11 rounded-lg border px-3" name="required" defaultValue={requirement.required ? "yes" : "no"}><option value="no">Not required</option><option value="yes">Required</option></select><select className="min-h-11 rounded-lg border px-3" name="templateVersionId" defaultValue={requirement.templateVersionId ?? ""}><option value="">Select published Permission Slip</option>{versions.map((v) => <option value={v.versionId} key={v.versionId}>{v.label}</option>)}</select><button className="min-h-11 rounded-lg bg-sky-700 px-4 font-semibold text-white" disabled={pending}>{pending ? "Saving…" : "Save requirement"}</button>{state.message ? <p className="md:col-span-3 text-sm">{state.message}</p> : null}</form>{requirement.required && requirement.templateVersionId ? <a className="font-semibold text-sky-800" href={`/api/forms/templates/${requirement.templateVersionId}/download`}>View, download, or print assigned blank permission slip</a> : null}</section>;
}
