import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireCapability } from "@/features/auth/services/authorization-service";
import { CancelAssignmentForm, ScheduleAssignmentForm, ScheduleLifecycleForm, ScheduleLocationForm, SchedulePositionForm } from "@/features/scheduling/components/scheduling-forms";
import { getScheduleWorkspace, listCandidates, listScheduleConflictHistory, listScheduleLocations, listSchedulingEventOptions } from "@/features/scheduling/services/scheduling-service";
import { formatScheduleDateTime } from "@/features/scheduling/utils/scheduling-datetime";

export const metadata: Metadata = { title: "Schedule Workspace" };
const sections = ["overview", "positions", "assignments", "conflicts", "lifecycle"] as const;
type Section = typeof sections[number];

export default async function ScheduleWorkspacePage({ params, searchParams }: Readonly<{ params: Promise<{ scheduleId: string }>; searchParams: Promise<{ section?: string; created?: string; notice?: string }> }>) {
  const account = await requireCapability("scheduling.view"); const manager = ["platform_administrator", "youth_pastor", "staff_member"].includes(account.role);
  const [{ scheduleId }, query] = await Promise.all([params, searchParams]);
  const rows = await getScheduleWorkspace(scheduleId); if (!rows.length) notFound();
  const schedule = rows[0]; const requested = query.section; const section: Section = manager && sections.includes(requested as Section) ? requested as Section : "overview";
  const positions = [...new Map(rows.filter((row) => row.positionId).map((row) => [row.positionId, row])).values()];
  const assignments = [...new Map(rows.filter((row) => row.assignmentId).map((row) => [row.assignmentId, row])).values()];
  const [locations, candidates, conflictHistory, eventOptions] = manager ? await Promise.all([listScheduleLocations(scheduleId), listCandidates(), listScheduleConflictHistory(scheduleId), listSchedulingEventOptions()]) : [[], [], [], []];
  const linkedEventName = schedule.eventId ? eventOptions.find((event) => event.eventId === schedule.eventId)?.eventName : null;
  return <div className="space-y-6">
    <Link className="text-sm font-semibold text-sky-700" href="/scheduling">← Back to Scheduling</Link>
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-sky-700">Schedule workspace</p><h1 className="mt-1 text-3xl font-bold">{schedule.scheduleName}</h1><p className="mt-2 text-slate-600">{formatScheduleDateTime(schedule.startsAt, schedule.timezone)} – {formatScheduleDateTime(schedule.endsAt, schedule.timezone)} · {schedule.timezone}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 font-semibold capitalize">{schedule.status}</span></header>
    {query.created === "1" ? <p className="rounded-lg bg-emerald-50 p-3 text-emerald-800">Draft schedule created. Add its positions and assignments here.</p> : null}
    {query.notice && ((section === "positions" && ["location-added", "position-added"].includes(query.notice)) || (section === "assignments" && ["volunteer-assigned", "assignment-cancelled"].includes(query.notice))) ? <p className="rounded-lg bg-emerald-50 p-3 text-emerald-800">{query.notice === "location-added" ? "Location added." : query.notice === "position-added" ? "Position added." : query.notice === "volunteer-assigned" ? "Volunteer assigned." : "Assignment cancelled and retained in history."}</p> : null}
    {manager ? <nav className="overflow-x-auto rounded-xl border bg-white p-2" aria-label="Schedule workspace sections"><div className="flex min-w-max gap-1">{sections.map((item) => <Link aria-current={section === item ? "page" : undefined} className={`min-h-11 rounded-lg px-4 py-3 text-sm font-semibold capitalize ${section === item ? "bg-sky-700 text-white" : "text-slate-700 hover:bg-slate-100"}`} href={`/scheduling/${scheduleId}?section=${item}`} key={item}>{item}</Link>)}</div></nav> : null}

    {section === "overview" ? <section className="grid gap-4 md:grid-cols-2"><article className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Schedule details</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-semibold">Ministry context</dt><dd>{schedule.ministryContext ?? "Not specified"}</dd></div><div><dt className="font-semibold">Linked Event</dt><dd>{schedule.eventId ? linkedEventName ?? "Linked Event" : "No linked Event"}</dd></div><div><dt className="font-semibold">Notes</dt><dd>{schedule.notes ?? "No notes"}</dd></div></dl></article><article className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Coverage summary</h2><p className="mt-4 text-3xl font-bold">{positions.length}</p><p className="text-sm text-slate-600">required position{positions.length === 1 ? "" : "s"}</p><p className="mt-3 text-lg font-semibold">{assignments.length} active assignment{assignments.length === 1 ? "" : "s"}</p><p className="mt-1 text-sm text-slate-600">{conflictHistory.length} assignment{conflictHistory.length === 1 ? "" : "s"} with retained conflict evidence</p></article></section> : null}

    {section === "positions" ? <section className="space-y-4"><h2 className="text-2xl font-bold">Positions and locations</h2><div className="grid gap-3 md:grid-cols-2">{positions.map((position) => <article className="rounded-xl border bg-white p-4" key={position.positionId}><h3 className="font-bold">{position.responsibility}</h3><p className="text-sm text-slate-600">{position.locationName ?? "No location"} · {position.requiredCount ?? 1} required</p></article>)}</div>{!positions.length ? <p className="rounded-xl border bg-white p-5 text-slate-600">No required positions have been added.</p> : null}{schedule.status === "draft" ? <div className="grid gap-4 lg:grid-cols-2"><ScheduleLocationForm scheduleId={scheduleId} /><SchedulePositionForm locations={locations} scheduleId={scheduleId} /></div> : <p className="text-sm text-slate-600">Positions can be changed only while the schedule is a draft.</p>}</section> : null}

    {section === "assignments" ? <section className="space-y-4"><h2 className="text-2xl font-bold">Volunteer assignments</h2><div className="grid gap-3 md:grid-cols-2">{assignments.map((assignment) => <article className="rounded-xl border bg-white p-4" key={assignment.assignmentId}><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="text-lg font-bold">{assignment.volunteerName}</h3><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold capitalize">{assignment.assignmentStatus}</span></div><p className="mt-3 font-semibold">{assignment.responsibility ?? "Unspecified responsibility"}</p><p className="text-sm text-slate-600">{assignment.locationName ?? "No location specified"}</p>{assignment.assignmentStartsAt && assignment.assignmentEndsAt ? <p className="mt-2 text-sm text-slate-600">{formatScheduleDateTime(assignment.assignmentStartsAt, schedule.timezone)} – {formatScheduleDateTime(assignment.assignmentEndsAt, schedule.timezone)}</p> : null}{assignment.assignmentId ? <CancelAssignmentForm id={assignment.assignmentId} scheduleId={scheduleId} /> : null}</article>)}</div>{!assignments.length ? <p className="rounded-xl border bg-white p-5 text-slate-600">No active assignments.</p> : null}{schedule.status === "draft" ? <div className="grid gap-4 xl:grid-cols-2">{positions.map((position) => <ScheduleAssignmentForm candidates={candidates} position={position} schedule={schedule} key={position.positionId} />)}</div> : null}</section> : null}

    {section === "conflicts" ? <section className="space-y-4"><h2 className="text-2xl font-bold">Conflict history</h2><p className="text-slate-600">Authorized managers can review retained conflict evidence for current and cancelled assignments. Cancellation does not reactivate or remove an assignment.</p>{conflictHistory.map((conflict) => <article className="rounded-xl border border-amber-200 bg-amber-50 p-4" key={conflict.assignmentId}><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-bold">{conflict.volunteerName} · {conflict.responsibility}</h3><span className="rounded-full bg-white px-3 py-1 text-sm font-semibold capitalize">{conflict.assignmentStatus}</span></div><p className="mt-2 text-sm text-amber-900"><span className="font-semibold">Conflict:</span> {conflict.conflictCodes.join(", ")}</p><p className="mt-1 text-sm text-amber-900"><span className="font-semibold">Location:</span> {conflict.locationName ?? "No location specified"}</p><p className="mt-1 text-sm text-amber-900"><span className="font-semibold">Assignment window:</span> {formatScheduleDateTime(conflict.assignmentStartsAt, schedule.timezone)} – {formatScheduleDateTime(conflict.assignmentEndsAt, schedule.timezone)}</p>{conflict.conflictOverridden ? <p className="mt-2 text-sm text-amber-950"><span className="font-semibold">Override reason:</span> {conflict.overrideReason ?? "No reason retained"}</p> : <p className="mt-2 text-sm font-semibold text-amber-950">Conflict detected without an override.</p>}</article>)}{!conflictHistory.length ? <p className="rounded-xl border bg-white p-5 text-slate-600">No retained assignment conflicts.</p> : null}</section> : null}

    {section === "lifecycle" ? <section className="space-y-4"><div><h2 className="text-2xl font-bold">Lifecycle</h2><p className="mt-1 text-slate-600">Publishing still enforces required-position coverage unless an explicit unfilled override is selected.</p></div><ScheduleLifecycleForm schedule={schedule} /></section> : null}
  </div>;
}
