import "server-only";
import { createClient } from "@/lib/supabase/server";
import type { RecurrencePattern, Rotation, RotationStatus, ScheduleAssignmentStatus, ScheduleConflictHistory, ScheduleRow, ScheduleStatus, SchedulingCandidate, SchedulingEventOption } from "@/features/scheduling/types/scheduling";

type Result<T> = Promise<{ data: T | null; error: unknown }>;
type Rpc = { rpc(name: string, args?: Record<string, unknown>): Result<unknown> };
async function rpc<T>(name: string, args: Record<string, unknown> = {}) { const client = await createClient() as unknown as Rpc; const { data, error } = await client.rpc(name, args); if (error) { console.error(`Scheduling RPC ${name} failed`, error); return null; } return data as T; }
async function rpcSucceeded(name: string, args: Record<string, unknown> = {}) { const client = await createClient() as unknown as Rpc; const { error } = await client.rpc(name, args); if (error) { console.error(`Scheduling RPC ${name} failed`, error); return false; } return true; }
const iso = (value: Date) => value.toISOString();
export async function listSchedules(from: Date, until: Date): Promise<ScheduleRow[]> { const rows = await rpc<Array<Record<string, unknown>>>("list_ministry_schedules", { p_from: iso(from), p_until: iso(until) }) ?? []; return rows.map((r) => ({ scheduleId:r.schedule_id as string,scheduleName:r.schedule_name as string,ministryContext:r.ministry_context as string|null,eventId:r.event_id as string|null,status:r.schedule_status as ScheduleStatus,startsAt:r.starts_at as string,endsAt:r.ends_at as string,timezone:r.timezone as string,notes:r.notes as string|null,positionId:r.position_id as string|null,responsibility:r.responsibility as string|null,requiredCount:r.required_count as number|null,locationId:r.location_id as string|null,locationName:r.location_name as string|null,assignmentId:r.assignment_id as string|null,profileId:r.profile_id as string|null,volunteerName:r.volunteer_name as string|null,assignmentStatus:r.assignment_status as ScheduleAssignmentStatus|null,assignmentStartsAt:r.assignment_starts_at as string|null,assignmentEndsAt:r.assignment_ends_at as string|null,conflictCodes:(r.conflict_codes as string[])??[],conflictOverridden:Boolean(r.conflict_overridden) })); }
export async function listCandidates(): Promise<SchedulingCandidate[]> { const rows=await rpc<Array<{profile_id:string;display_name:string}>>("list_scheduling_candidates")??[]; return rows.map(r=>({profileId:r.profile_id,displayName:r.display_name})); }
export async function listSchedulingEventOptions(): Promise<SchedulingEventOption[]> { const rows=await rpc<Array<Record<string,unknown>>>("list_schedulable_events")??[]; return rows.map(r=>({eventId:r.event_id as string,eventName:r.event_name as string,eventStatus:r.event_status as string,startsAt:r.starts_at as string,endsAt:r.ends_at as string,timezone:r.timezone as string})); }
export async function listScheduleLocations(scheduleId:string): Promise<Array<{id:string;name:string}>> { const rows=await rpc<Array<{location_id:string;location_name:string}>>("list_schedule_locations",{p_schedule_id:scheduleId})??[]; return rows.map(row=>({id:row.location_id,name:row.location_name})); }
export async function getScheduleWorkspace(scheduleId:string):Promise<ScheduleRow[]>{const rows=await listSchedules(new Date("1970-01-01T00:00:00.000Z"),new Date("9999-12-31T23:59:59.999Z"));return rows.filter(row=>row.scheduleId===scheduleId);}
export async function listScheduleConflictHistory(scheduleId:string):Promise<ScheduleConflictHistory[]>{const rows=await rpc<Array<Record<string,unknown>>>("list_schedule_assignment_conflict_history",{p_schedule_id:scheduleId})??[];return rows.map(row=>({assignmentId:row.assignment_id as string,positionId:row.position_id as string,volunteerName:row.volunteer_name as string,responsibility:row.responsibility as string,locationName:row.location_name as string|null,assignmentStatus:row.assignment_status as ScheduleAssignmentStatus,assignmentStartsAt:row.assignment_starts_at as string,assignmentEndsAt:row.assignment_ends_at as string,conflictCodes:(row.conflict_codes as string[])??[],conflictOverridden:Boolean(row.conflict_overridden),overrideReason:row.override_reason as string|null}));}
export async function createSchedule(v:{name:string;ministryContext:string|null;eventId:string|null;startsAt:Date;endsAt:Date;timezone:string;notes:string|null}) { return rpc<string>("create_ministry_schedule",{p_name:v.name,p_ministry_context:v.ministryContext,p_event_id:v.eventId,p_starts_at:iso(v.startsAt),p_ends_at:iso(v.endsAt),p_timezone:v.timezone,p_notes:v.notes}); }
export async function addLocation(v:{scheduleId:string;name:string;notes:string|null}) { return rpc<string>("add_schedule_location",{p_schedule_id:v.scheduleId,p_name:v.name,p_notes:v.notes}); }
export async function addPosition(v:{scheduleId:string;locationId:string|null;responsibility:string;requiredCount:number}) { return rpc<string>("add_schedule_position",{p_schedule_id:v.scheduleId,p_location_id:v.locationId,p_responsibility:v.responsibility,p_required_count:v.requiredCount,p_starts_at:null,p_ends_at:null}); }
export async function assignPosition(v:{positionId:string;profileId:string;startsAt:Date;endsAt:Date;override:boolean;overrideReason:string|null}) { return rpc<string>("assign_schedule_position",{p_position_id:v.positionId,p_profile_id:v.profileId,p_starts_at:iso(v.startsAt),p_ends_at:iso(v.endsAt),p_override:v.override,p_override_reason:v.overrideReason}); }
export async function setScheduleStatus(id:string,status:ScheduleStatus,allow:boolean) { return rpcSucceeded("set_ministry_schedule_status",{p_schedule_id:id,p_status:status,p_allow_unfilled:allow}); }
export async function cancelAssignment(id:string) { return rpcSucceeded("cancel_schedule_assignment",{p_assignment_id:id}); }
export async function listRotations():Promise<Rotation[]> { const rows=await rpc<Array<Record<string,unknown>>>("list_schedule_rotations")??[]; return rows.map(r=>({id:r.id as string,name:r.name as string,recurrencePattern:r.recurrence_pattern as RecurrencePattern,weekday:r.weekday as number|null,monthlyOrdinal:r.monthly_ordinal as number|null,startsOn:r.starts_on as string,endsOn:r.ends_on as string|null,startsAt:r.starts_at as string,endsAt:r.ends_at as string,timezone:r.timezone as string,scheduleName:r.schedule_name as string,ministryContext:r.ministry_context as string|null,responsibility:r.responsibility as string,locationName:r.location_name as string|null,profileId:r.profile_id as string|null,status:r.status as RotationStatus})); }
export async function createRotation(v:Record<string,unknown>) { return rpc<string>("create_schedule_rotation",v); }
export async function setRotationStatus(id:string,status:RotationStatus) { return rpcSucceeded("set_schedule_rotation_status",{p_rotation_id:id,p_status:status}); }
export async function generateRotation(id:string,through:string) { return rpc<number>("generate_schedule_rotation",{p_rotation_id:id,p_through:through}); }
