"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";
import{customAssignmentSchema,customFieldSchema,customTemplateSchema,customVersionSchema}from"@/features/forms/schemas/custom-form-schema";
import{isDuplicateCustomFormAssignmentError,runCustomFormRpc}from"@/features/forms/services/custom-form-service";import type{CustomFormActionState}from"@/features/forms/types/custom-forms";
const ok=(message:string):CustomFormActionState=>({success:true,message}),bad=(e:unknown):CustomFormActionState=>({success:false,message:e instanceof Error?e.message:"Custom Form action denied."});
export async function createCustomTemplateAction(_:CustomFormActionState,fd:FormData){const p=customTemplateSchema.safeParse(Object.fromEntries(fd));if(!p.success)return bad(new Error("Review the template."));try{await runCustomFormRpc("create_custom_form_template",{p_name:p.data.name,p_description:p.data.description});revalidatePath("/permission-forms");return ok("Custom Form template created.")}catch(e){return bad(e)}}
export async function createCustomVersionAction(_:CustomFormActionState,fd:FormData){const p=customVersionSchema.safeParse(Object.fromEntries(fd));if(!p.success)return bad(new Error("Review the version."));try{await runCustomFormRpc("create_custom_form_version",{p_template_id:p.data.templateId,p_title:p.data.title,p_instructions:p.data.instructions});revalidatePath("/permission-forms");return ok("Draft version created.")}catch(e){return bad(e)}}
export async function saveCustomFieldAction(_:CustomFormActionState,fd:FormData){const p=customFieldSchema.safeParse(Object.fromEntries(fd));if(!p.success)return bad(new Error("Review the controlled field."));try{await runCustomFormRpc("save_custom_form_field",{p_version_id:p.data.versionId,p_field_id:null,p_field_key:p.data.fieldKey,p_field_type:p.data.fieldType,p_label:p.data.label,p_help_text:p.data.helpText,p_is_required:p.data.isRequired,p_display_order:p.data.displayOrder,p_minimum_length:null,p_maximum_length:null,p_minimum_date:null,p_maximum_date:null,p_choice_options:p.data.choiceOptions});revalidatePath("/permission-forms");return ok("Draft field saved.")}catch(e){return bad(e)}}
export async function publishCustomVersionAction(fd:FormData){await runCustomFormRpc("publish_custom_form_version",{p_version_id:String(fd.get("versionId"))});revalidatePath("/permission-forms")}
export async function retireCustomVersionAction(fd:FormData){await runCustomFormRpc("retire_custom_form_version",{p_version_id:String(fd.get("versionId"))});revalidatePath("/permission-forms")}
export async function archiveCustomTemplateAction(fd:FormData){await runCustomFormRpc("archive_custom_form_template",{p_template_id:String(fd.get("templateId"))});revalidatePath("/permission-forms")}
export async function createCustomAssignmentAction(_:CustomFormActionState,fd:FormData){const p=customAssignmentSchema.safeParse(Object.fromEntries(fd));if(!p.success)return bad(new Error(p.error.issues[0]?.message??"Review the assignment target."));const t=p.data.targetId;try{await runCustomFormRpc("create_custom_form_assignment",{p_version_id:p.data.versionId,p_assignment_type:p.data.assignmentType,p_event_id:p.data.assignmentType==="event"?t:null,p_student_id:p.data.assignmentType==="student"?t:null,p_household_id:p.data.assignmentType==="household"?t:null,p_volunteer_profile_id:p.data.assignmentType==="volunteer"?t:null});revalidatePath("/permission-forms");return ok("Custom Form assigned.")}catch(e){return bad(isDuplicateCustomFormAssignmentError(e)?new Error("This form is already assigned to that target."):e)}}
export async function archiveCustomAssignmentAction(fd:FormData){await runCustomFormRpc("archive_custom_form_assignment",{p_assignment_id:String(fd.get("assignmentId"))});revalidatePath("/permission-forms")}
export async function saveCustomAnswerAction(fd:FormData){const assignmentId=String(fd.get("assignmentId")),submissionId=String(fd.get("submissionId")),fieldId=String(fd.get("fieldId")),kind=String(fd.get("fieldType")),raw=fd.getAll("value").map(String);await runCustomFormRpc("save_custom_form_answer",{p_submission_id:submissionId,p_field_id:fieldId,p_text_value:["short_text","long_text"].includes(kind)?raw[0]||null:null,p_boolean_value:["yes_no","acknowledgment"].includes(kind)?raw[0]==="true":null,p_date_value:kind==="date"?raw[0]||null:null,p_choice_value:kind==="single_choice"?raw[0]||null:null,p_multiple_choice_value:kind==="multiple_choice"?raw:null});revalidatePath(`/permission-forms/my/${assignmentId}`)}
export async function submitCustomFormAction(fd:FormData){const id=String(fd.get("submissionId"));await runCustomFormRpc("submit_custom_form",{p_submission_id:id});revalidatePath("/permission-forms");redirect("/permission-forms")}
export async function archiveCustomSubmissionAction(fd:FormData){await runCustomFormRpc("archive_custom_form_submission",{p_submission_id:String(fd.get("submissionId"))});revalidatePath("/permission-forms")}
