"use server";
import{revalidatePath}from"next/cache";
import{staffVisitorCardSchema,visitorConversionSchema,visitorLinkSchema,visitorReasonSchema}from"@/features/forms/schemas/visitor-card-schema";
import{runVisitorCardRpc}from"@/features/forms/services/visitor-card-service";
import type{VisitorCardActionState}from"@/features/forms/types/visitor-cards";

const ok=(message:string):VisitorCardActionState=>({success:true,message});const bad=(error:unknown):VisitorCardActionState=>({success:false,message:error instanceof Error?error.message:"Visitor Card action was denied."});
export async function createStaffVisitorCardAction(_:VisitorCardActionState,formData:FormData){const parsed=staffVisitorCardSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return bad(new Error(parsed.error.issues[0]?.message??"Review the Visitor Card."));const v=parsed.data;try{await runVisitorCardRpc("create_staff_visitor_card",{p_event_id:v.eventId,p_visit_date:v.visitDate,p_youth_first_name:v.youthFirstName,p_youth_last_name:v.youthLastName,p_guardian_name:v.guardianName,p_email:v.email,p_phone:v.phone,p_grade_or_age_group:v.gradeOrAgeGroup,p_invited_by:v.invitedBy,p_how_heard:v.howHeard,p_follow_up_email:v.followUpEmail,p_follow_up_phone:v.followUpPhone,p_follow_up_notes:v.followUpNotes});revalidatePath("/visitors");return ok("Visitor Card created and added to the review queue.")}catch(error){return bad(error)}}

const lifecycleRpc:Record<string,string>={begin:"begin_visitor_card_review",flag_duplicate:"flag_visitor_card_possible_duplicate",clear_duplicate:"clear_visitor_card_duplicate",start_conversion:"start_visitor_card_conversion",complete_conversion:"complete_visitor_card_conversion",close:"close_visitor_card",reopen:"reopen_visitor_card",archive:"archive_visitor_card"};
export async function visitorCardLifecycleAction(_:VisitorCardActionState,formData:FormData){const parsed=visitorReasonSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return bad(new Error("Review this workflow action."));const rpc=lifecycleRpc[parsed.data.operation];if(!rpc)return bad(new Error("Unknown Visitor Card action."));try{const args:Record<string,unknown>={p_visitor_card_id:parsed.data.visitorCardId};if(["flag_duplicate","clear_duplicate","close","reopen","archive"].includes(parsed.data.operation))args.p_reason=parsed.data.reason;await runVisitorCardRpc(rpc,args);revalidatePath("/visitors");revalidatePath(`/visitors/${parsed.data.visitorCardId}`);return ok("Visitor Card workflow updated.")}catch(error){return bad(error)}}
export async function linkVisitorCardAction(_:VisitorCardActionState,formData:FormData){const parsed=visitorLinkSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return bad(new Error(parsed.error.issues[0]?.message??"Review the link."));try{await runVisitorCardRpc("link_visitor_card_existing",{p_visitor_card_id:parsed.data.visitorCardId,p_link_type:parsed.data.linkType,p_target_id:parsed.data.targetId,p_reason:parsed.data.reason});revalidatePath(`/visitors/${parsed.data.visitorCardId}`);return ok("Existing ministry record linked.")}catch(error){return bad(error)}}
export async function recordVisitorConversionAction(_:VisitorCardActionState,formData:FormData){const parsed=visitorConversionSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return bad(new Error(parsed.error.issues[0]?.message??"Review conversion evidence."));try{await runVisitorCardRpc("record_visitor_card_conversion",{p_visitor_card_id:parsed.data.visitorCardId,p_person_id:parsed.data.personId,p_student_id:parsed.data.studentId,p_household_id:parsed.data.householdId,p_reason:parsed.data.reason});revalidatePath(`/visitors/${parsed.data.visitorCardId}`);return ok("Conversion evidence retained.")}catch(error){return bad(error)}}
