import "server-only";
import { createClient } from "@/lib/supabase/server";
import type { AttendanceTrend, CoverageRow, EventParticipationTrend, EventReportRow, ReportType, ReportingOverview, SavedReport, VolunteerActivityRow } from "@/features/reporting/types/reporting";

type RpcResult = Promise<{ data: unknown; error: { message?: string } | null }>;
type RpcClient = { rpc(name: string, args?: Record<string, unknown>): RpcResult };
async function call<T>(name:string,args:Record<string,unknown>={}) { const client=await createClient() as unknown as RpcClient; const {data,error}=await client.rpc(name,args); if(error) throw new Error(error.message??`Reporting RPC ${name} failed`); return data as T; }
const num=(value:unknown)=>Number(value??0);

export async function getReportingOverview(fromDate:string,toDate:string):Promise<ReportingOverview>{const row=await call<Record<string,unknown>>("get_reporting_overview",{p_from:fromDate,p_to:toDate});return {fromDate,toDate,attendanceCount:num(row.attendanceCount),uniqueYouth:num(row.uniqueYouth),firstTimeParticipants:num(row.firstTimeParticipants),firstTimeVisitorActivity:num(row.firstTimeVisitorActivity),activeYouth:num(row.activeYouth),newYouthAdded:num(row.newYouthAdded),activeHouseholds:num(row.activeHouseholds),newHouseholds:num(row.newHouseholds),eventAttendance:num(row.eventAttendance),upcomingEvents:num(row.upcomingEvents),registrations:num(row.registrations),requiredPositions:num(row.requiredPositions),filledPositions:num(row.filledPositions),unfilledPositions:num(row.unfilledPositions),coveragePercentage:num(row.coveragePercentage),upcomingAssignments:num(row.upcomingAssignments)};}
export async function listAttendanceTrends(fromDate:string,toDate:string,interval:"week"|"month"):Promise<AttendanceTrend[]>{const rows=await call<Array<Record<string,unknown>>>("list_attendance_report_trends",{p_from:fromDate,p_to:toDate,p_interval:interval});return rows.map(r=>({bucketStart:String(r.bucket_start),attendanceCount:num(r.attendance_count),uniqueYouth:num(r.unique_youth)}));}
export async function listEventReports(fromDate:string,toDate:string):Promise<EventReportRow[]>{const rows=await call<Array<Record<string,unknown>>>("list_event_report_summary",{p_from:fromDate,p_to:toDate});return rows.map(r=>({eventId:String(r.event_id),eventName:String(r.event_name),eventType:String(r.event_type),startsAt:String(r.starts_at),capacity:r.capacity===null?null:num(r.capacity),registeredCount:num(r.registered_count),waitlistedCount:num(r.waitlisted_count),cancelledCount:num(r.cancelled_count),attendanceCount:num(r.attendance_count),capacityUtilization:r.capacity_utilization===null?null:num(r.capacity_utilization),volunteerStaffing:num(r.volunteer_staffing)}));}
export async function listEventParticipationTrends(fromDate:string,toDate:string):Promise<EventParticipationTrend[]>{const rows=await call<Array<Record<string,unknown>>>("list_event_participation_trends",{p_from:fromDate,p_to:toDate,p_interval:"month"});return rows.map(r=>({bucketStart:String(r.bucket_start),registrationCount:num(r.registration_count),attendanceCount:num(r.attendance_count)}));}
export async function listVolunteerActivity(fromDate:string,toDate:string):Promise<VolunteerActivityRow[]>{const rows=await call<Array<Record<string,unknown>>>("list_volunteer_assignment_activity",{p_from:fromDate,p_to:toDate});return rows.map(r=>({source:r.source as VolunteerActivityRow["source"],assignmentId:String(r.assignment_id),profileId:String(r.profile_id),volunteerName:String(r.volunteer_name),responsibility:String(r.responsibility),assignmentStatus:String(r.assignment_status),startsAt:String(r.starts_at),eventName:String(r.event_name)}));}
export async function listCoverage(fromDate:string,toDate:string):Promise<CoverageRow[]>{const rows=await call<Array<Record<string,unknown>>>("list_scheduling_coverage_report",{p_from:fromDate,p_to:toDate});return rows.map(r=>({scheduleId:String(r.schedule_id),scheduleName:String(r.schedule_name),startsAt:String(r.starts_at),scheduleStatus:String(r.schedule_status),requiredPositions:num(r.required_positions),filledPositions:num(r.filled_positions),unfilledPositions:num(r.unfilled_positions),coveragePercentage:num(r.coverage_percentage)}));}
export async function listSavedReports():Promise<SavedReport[]>{const rows=await call<Array<Record<string,unknown>>>("list_my_saved_reports");return rows.map(r=>({id:String(r.id),name:String(r.name),reportType:r.report_type as ReportType,configuration:r.configuration as Record<string,unknown>,createdAt:String(r.created_at),updatedAt:String(r.updated_at)}));}
export const createSavedReport=(name:string,reportType:ReportType,configuration:Record<string,unknown>)=>call<string>("create_saved_report",{p_name:name,p_report_type:reportType,p_configuration:configuration});
export const renameSavedReport=(id:string,name:string)=>call<null>("rename_saved_report",{p_id:id,p_name:name});
export const archiveSavedReport=(id:string)=>call<null>("archive_saved_report",{p_id:id});
export const recordReportingExport=(reportType:ReportType,format:"csv"|"xlsx",fromDate:string,toDate:string,rowCount:number)=>call<null>("record_reporting_export",{p_report_type:reportType,p_format:format,p_from:fromDate,p_to:toDate,p_row_count:rowCount});
