import Link from "next/link";
import type { AttendanceSessionReport,CheckInEventReport } from "@/features/attendance/types/attendance-reports";
import { archiveSavedReportAction,createSavedReportAction,renameSavedReportAction } from "@/features/reporting/actions/saved-report-actions";
import { PrintReportButton } from "@/features/reporting/components/print-report-button";
import type { ReportingData,ReportingRange } from "@/features/reporting/types/reporting";

const fmt=(value:string)=>new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const sections=["overview","attendance","events","volunteers","growth","ministry-health","saved-reports"];
const Metric=({label,value,detail}:{label:string;value:string|number;detail:string})=><article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></article>;
const ExportLinks=({report,range}:{report:string;range:ReportingRange})=><span className="flex gap-2 print:hidden"><Link className="rounded border border-slate-300 px-3 py-1 text-sm font-semibold" href={`/reports/export?report=${report}&format=csv&from=${range.fromDate}&to=${range.toDate}`}>CSV</Link><Link className="rounded border border-slate-300 px-3 py-1 text-sm font-semibold" href={`/reports/export?report=${report}&format=xlsx&from=${range.fromDate}&to=${range.toDate}`}>Excel</Link></span>;

export function ReportingWorkspace({data,range,attendanceSessions,checkIns}:{data:ReportingData;range:ReportingRange;attendanceSessions:AttendanceSessionReport[];checkIns:CheckInEventReport[]}){const o=data.overview;return <div className="space-y-10">
  <header><p className="text-sm font-semibold text-sky-700">Ministry operations</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Reporting & Analytics</h1><p className="mt-2 max-w-3xl text-slate-600">Live, authorized ministry metrics. Attendance, registration, and check-in remain separately labeled.</p></header>
  <nav className="flex flex-wrap gap-2 print:hidden" aria-label="Report sections">{sections.map(s=><a className="rounded-full bg-slate-100 px-3 py-2 text-sm font-semibold text-slate-700" href={`#${s}`} key={s}>{s.replace("-"," ")}</a>)}</nav>
  <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm print:hidden"><div className="mb-4 flex flex-wrap gap-2"><Link className="rounded border px-3 py-2 text-sm font-semibold" href="/reports?preset=30">Last 30 days</Link><Link className="rounded border px-3 py-2 text-sm font-semibold" href="/reports?preset=90">Last 90 days</Link><Link className="rounded border px-3 py-2 text-sm font-semibold" href="/reports?preset=ytd">Year to date</Link><Link className="rounded border px-3 py-2 text-sm font-semibold" href="/reports?preset=365">Last 12 months</Link></div><form className="flex flex-wrap items-end gap-3"><label className="text-sm font-semibold">From<input className="mt-1 block min-h-11 rounded border border-slate-300 px-3" defaultValue={range.fromDate} name="from" required type="date"/></label><label className="text-sm font-semibold">To<input className="mt-1 block min-h-11 rounded border border-slate-300 px-3" defaultValue={range.toDate} name="to" required type="date"/></label><button className="min-h-11 rounded bg-sky-700 px-5 font-semibold text-white">Run custom range</button><PrintReportButton/></form><p className="mt-3 text-xs text-slate-500">Maximum range: 366 days. Current window: {range.fromDate} through {range.toDate}.</p></section>
  <section className="space-y-4" id="overview"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Overview</h2><p className="text-sm text-slate-600">Aggregate operational signals for the selected window.</p></div><ExportLinks range={range} report="overview"/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Unique youth attending" value={o.uniqueYouth} detail="Each youth counts once per reporting day across finalized present attendance."/><Metric label="First-time participants" value={o.firstTimeParticipants} detail="Youth whose first finalized present attendance occurred in this window."/><Metric label="Registrations" value={o.registrations} detail="Registered, confirmed, or completed Event registrations; not attendance."/><Metric label="Scheduling coverage" value={`${o.coveragePercentage}%`} detail={`${o.filledPositions} filled of ${o.requiredPositions} required positions.`}/></div></section>
  <section className="space-y-4" id="attendance"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Attendance</h2><p className="text-sm text-slate-600">Finalized present records are authoritative for trends; check-in is separate.</p></div><ExportLinks range={range} report="attendance"/></div><div className="grid gap-6 lg:grid-cols-2"><TrendTable title="Weekly trends" rows={data.weeklyTrends}/><TrendTable title="Monthly trends" rows={data.monthlyTrends}/></div><SimpleTable headers={["Date","Event / class","Present","Absent","Excused","Pending"]} rows={attendanceSessions.map(s=>[s.sessionDate,`${s.eventName} — ${s.className}`,s.presentCount,s.absentCount,s.excusedCount,s.pendingCount])} empty="No attendance sessions in this range."/><SimpleTable headers={["Event check-in","Still in","Checked out","Exceptions","First-time visitor activity"]} rows={checkIns.map(e=>[e.eventName,e.checkedInCount,e.checkedOutCount,e.exceptionCount,e.visitorCount])} empty="No check-in activity in this range."/></section>
  <section className="space-y-4" id="events"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Events</h2><p className="text-sm text-slate-600">Registration and finalized attendance are intentionally separate.</p></div><ExportLinks range={range} report="events"/></div><SimpleTable headers={["Period","Registrations","Attendance"]} rows={data.eventTrends.map(e=>[e.bucketStart,e.registrationCount,e.attendanceCount])} empty="No Event participation trends in this range."/><SimpleTable headers={["Event","Date","Registered","Waitlisted","Attendance","Capacity use","Volunteers"]} rows={data.events.map(e=>[e.eventName,fmt(e.startsAt),e.registeredCount,e.waitlistedCount,e.attendanceCount,e.capacityUtilization===null?"Not set":`${e.capacityUtilization}%`,e.volunteerStaffing])} empty="No events in this range."/></section>
  <section className="space-y-4" id="volunteers"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Volunteers</h2><p className="text-sm text-slate-600">Scheduling is authoritative where present; legacy Event assignments fill historical gaps. {o.upcomingAssignments} upcoming assignments are currently active.</p></div><ExportLinks range={range} report="volunteers"/></div><SimpleTable headers={["Volunteer","Responsibility","Activity","Status","Source"]} rows={data.volunteerActivity.map(a=>[a.volunteerName,a.responsibility,`${a.eventName} — ${fmt(a.startsAt)}`,a.assignmentStatus,a.source==="scheduling"?"Scheduling":"Legacy Event"])} empty="No volunteer assignment activity in this range."/><SimpleTable headers={["Schedule","Required","Filled","Unfilled","Coverage"]} rows={data.coverage.map(c=>[`${c.scheduleName} — ${fmt(c.startsAt)}`,c.requiredPositions,c.filledPositions,c.unfilledPositions,`${c.coveragePercentage}%`])} empty="No Scheduling coverage in this range."/></section>
  <section className="space-y-4" id="growth"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Growth</h2><p className="text-sm text-slate-600">Record creation and first participation are shown as distinct measures.</p></div><ExportLinks range={range} report="growth"/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Active youth" value={o.activeYouth} detail="Students currently using the existing active lifecycle status."/><Metric label="New youth added" value={o.newYouthAdded} detail="Student records created during the selected window."/><Metric label="First-time participants" value={o.firstTimeParticipants} detail="First finalized present attendance occurred during the window."/><Metric label="Active households" value={o.activeHouseholds} detail="Households currently using the existing active lifecycle status."/><Metric label="New households" value={o.newHouseholds} detail="Household records created during the selected window."/><Metric label="First-time visitor activity" value={o.firstTimeVisitorActivity} detail="Visitor check-in records; no returning-visitor continuity is claimed."/></div></section>
  <section className="space-y-4" id="ministry-health"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Ministry Health</h2><p className="text-sm text-slate-600">Transparent individual measures only—no composite score.</p></div><ExportLinks range={range} report="ministry_health"/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Participation" value={o.uniqueYouth} detail="Unique daily youth attendance in the selected window."/><Metric label="Growth" value={o.newYouthAdded} detail="New youth records; first-time participants are shown separately above."/><Metric label="Events" value={o.upcomingEvents} detail="Currently published or active upcoming events."/><Metric label="Volunteer operations" value={`${o.coveragePercentage}%`} detail="Current selected-window Scheduling coverage."/></div></section>
  <section className="space-y-4 print:hidden" id="saved-reports"><h2 className="text-2xl font-bold">Saved Reports</h2><p className="text-sm text-slate-600">Private configurations only. Running one always uses current authorized data.</p><form action={createSavedReportAction} className="flex flex-wrap gap-3 rounded-xl border border-slate-200 bg-white p-4"><input className="min-h-11 rounded border px-3" name="name" placeholder="Report name" required/><select className="min-h-11 rounded border px-3" name="reportType"><option value="overview">Overview</option><option value="attendance">Attendance</option><option value="events">Events</option><option value="volunteers">Volunteers</option><option value="growth">Growth</option><option value="ministry_health">Ministry Health</option></select><input name="fromDate" type="hidden" value={range.fromDate}/><input name="toDate" type="hidden" value={range.toDate}/><button className="rounded bg-sky-700 px-4 font-semibold text-white">Save current filters</button></form><div className="space-y-3">{data.savedReports.map(r=><article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4" key={r.id}><div><h3 className="font-semibold">{r.name}</h3><p className="text-xs text-slate-500">{r.reportType.replace("_"," ")} · private</p></div><div className="flex flex-wrap gap-2"><Link className="rounded border px-3 py-2 text-sm font-semibold" href={`/reports?preset=custom&from=${String(r.configuration.fromDate??range.fromDate)}&to=${String(r.configuration.toDate??range.toDate)}#${r.reportType.replace("_","-")}`}>Run</Link><form action={renameSavedReportAction}><input name="id" type="hidden" value={r.id}/><input className="rounded border px-2 py-2 text-sm" defaultValue={r.name} name="name" required/><button className="ml-1 rounded border px-3 py-2 text-sm">Rename</button></form><form action={archiveSavedReportAction}><input name="id" type="hidden" value={r.id}/><button className="rounded border border-red-200 px-3 py-2 text-sm text-red-700">Delete</button></form></div></article>)}{data.savedReports.length===0?<p className="text-sm text-slate-500">No saved reports yet.</p>:null}</div></section>
  </div>}

function TrendTable({title,rows}:{title:string;rows:ReportingData["weeklyTrends"]}){return <div className="rounded-xl border bg-white p-4"><h3 className="font-bold">{title}</h3><SimpleTable headers={["Period","Attendance","Unique youth/day"]} rows={rows.map(r=>[r.bucketStart,r.attendanceCount,r.uniqueYouth])} empty="No finalized present attendance."/></div>}
function SimpleTable({headers,rows,empty}:{headers:string[];rows:(string|number)[][];empty:string}){return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr>{headers.map(h=><th className="px-4 py-3 font-semibold" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td className="px-4 py-3" key={j}>{cell}</td>)}</tr>)}{rows.length===0?<tr><td className="px-4 py-6 text-slate-500" colSpan={headers.length}>{empty}</td></tr>:null}</tbody></table></div>}
