"use server";
import { revalidatePath } from "next/cache";
import { assignmentIdSchema, assignmentSchema, generationSchema, lifecycleSchema, locationSchema, positionSchema, rotationSchema, rotationStatusSchema, scheduleSchema } from "@/features/scheduling/schemas/scheduling-schema";
import { addLocation, addPosition, assignPosition, cancelAssignment, createRotation, createSchedule, generateRotation, setRotationStatus, setScheduleStatus } from "@/features/scheduling/services/scheduling-service";
import type { SchedulingActionState } from "@/features/scheduling/types/scheduling";
const fail=(message:string):SchedulingActionState=>({success:false,message}); const done=(message:string):SchedulingActionState=>({success:true,message});
export async function createScheduleAction(_:SchedulingActionState,fd:FormData){const p=scheduleSchema.safeParse(Object.fromEntries(fd));if(!p.success)return fail("Review the schedule details.");if(!await createSchedule(p.data))return fail("The schedule could not be created.");revalidatePath("/scheduling");return done("Draft schedule created.");}
export async function addLocationAction(_:SchedulingActionState,fd:FormData){const p=locationSchema.safeParse(Object.fromEntries(fd));if(!p.success||!await addLocation(p.data))return fail("The location could not be added.");revalidatePath("/scheduling");return done("Location added.");}
export async function addPositionAction(_:SchedulingActionState,fd:FormData){const p=positionSchema.safeParse(Object.fromEntries(fd));if(!p.success||!await addPosition(p.data))return fail("The position could not be added.");revalidatePath("/scheduling");return done("Position added.");}
export async function assignPositionAction(_:SchedulingActionState,fd:FormData){const p=assignmentSchema.safeParse(Object.fromEntries(fd));if(!p.success||!await assignPosition(p.data))return fail("Assignment blocked. Review availability, overlaps, times, or provide an explicit override reason.");revalidatePath("/scheduling");return done("Volunteer assigned.");}
export async function scheduleLifecycleAction(_:SchedulingActionState,fd:FormData){const p=lifecycleSchema.safeParse(Object.fromEntries(fd));if(!p.success||!await setScheduleStatus(p.data.scheduleId,p.data.status,p.data.allowUnfilled))return fail("Lifecycle change was blocked. Resolve unfilled positions or explicitly allow them.");revalidatePath("/scheduling");return done(`Schedule ${p.data.status}.`);}
export async function cancelAssignmentAction(_:SchedulingActionState,fd:FormData){const p=assignmentIdSchema.safeParse(Object.fromEntries(fd));if(!p.success||!await cancelAssignment(p.data.assignmentId))return fail("Assignment could not be cancelled.");revalidatePath("/scheduling");return done("Assignment cancelled and retained in history.");}
export async function createRotationAction(_:SchedulingActionState,fd:FormData){const p=rotationSchema.safeParse(Object.fromEntries(fd));if(!p.success)return fail("Review the rotation details.");const v=p.data;if(!await createRotation({p_name:v.name,p_pattern:v.pattern,p_weekday:v.weekday,p_monthly_ordinal:v.monthlyOrdinal,p_starts_on:v.startsOn,p_ends_on:v.endsOn,p_starts_at:v.startsAt,p_ends_at:v.endsAt,p_timezone:v.timezone,p_schedule_name:v.scheduleName,p_ministry_context:v.ministryContext,p_responsibility:v.responsibility,p_location_name:v.locationName,p_profile_id:v.profileId}))return fail("Rotation could not be created.");revalidatePath("/scheduling");return done("Rotation created.");}
export async function rotationStatusAction(_:SchedulingActionState,fd:FormData){const p=rotationStatusSchema.safeParse(Object.fromEntries(fd));if(!p.success||!await setRotationStatus(p.data.rotationId,p.data.status))return fail("Rotation status could not be changed.");revalidatePath("/scheduling");return done(`Rotation ${p.data.status}.`);}
export async function generateRotationAction(_:SchedulingActionState,fd:FormData){const p=generationSchema.safeParse(Object.fromEntries(fd));if(!p.success)return fail("Choose a valid generation date.");const count=await generateRotation(p.data.rotationId,p.data.through);if(count===null)return fail("Occurrences could not be generated.");revalidatePath("/scheduling");return done(`${count} new occurrence${count===1?"":"s"} generated; existing history was unchanged.`);}
